AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  ping-service 
  Receive pipeline events from customer account

Parameters:
  Environment:
    Type: String
    # Default: sandbox

Resources:

  Ping:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub PingEvents-${Environment}

  PingEventsPolicy:
    Type: AWS::Events::EventBusPolicy
    Properties:
      EventBusName: !Sub PingEvents-${Environment}
      StatementId: !Sub 'AllowCrossAccountAndRegion-${Environment}'
      Statement: 
        Effect: Allow
        Action: events:PutEvents
        Principal:
          AWS: "*"
        Resource: !Sub "arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/${Ping}"
        Condition:
          ArnLike: 
            AWS:SourceArn: "arn:aws:events:*:*:rule/*"

  PingEventsRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub PingEventsRule-${Environment}
      EventBusName: !Sub PingEvents-${Environment}
      EventPattern: 
        source:
          - "aws.codepipeline"
      Targets:
        - Arn: !GetAtt PingFunction.Arn
          Id: "PingFunctionTarget"

  PingFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub PingFunctionRole-${Environment}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
                - s3.amazonaws.com
                - sqs.amazonaws.com
                - events.amazonaws.com
                - codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: AssumeRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource: arn:aws:iam::*:role/* # can assume any provider
        - PolicyName: SSMParameterAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:GetParameterHistory
                  - kms:Decrypt
                Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/thunder/*
        - PolicyName: CodePipelineAccessPolicy 
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - codepipeline:GetPipelineExecution
                Resource: arn:aws:codepipeline:*:*:*
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:PingFunction-${Environment}'
        - PolicyName: LambdaInvokePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                  - lambda:InvokeFunction
                  - events:InvokeFunction
                Resource: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:PingFunction-${Environment}'
            
  PingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'PingFunction-${Environment}'
      CodeUri: ./
      Handler: event.handler
      Role: !GetAtt PingFunctionRole.Arn
      Architectures:
        - x86_64
      Runtime: nodejs20.x
      MemorySize: 512
      Timeout: 180
      Environment:
        Variables:
          NODE_OPTIONS: --enable-source-maps false
          REGION: !Ref AWS::Region
      # Policies:
      #   - SSMParameterReadPolicy:
      #       ParameterName: /thunder/*
      #   - KMSDecryptPolicy:
      #       KeyId: alias/aws/ssm
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "ESNext"
        Sourcemap: false
        EntryPoints: 
          - src/event.ts
        External: 
          - '@aws-sdk/*'
          - '@supabase/supabase-js'
          - 'uuid'
          - '@plunk/node'
          - '@react-email/components'
          - '@react-email/render'
          - 'react'
          - 'react-dom'

  PingFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref PingFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt PingEventsRule.Arn

Outputs:
  PingFunctionRoleArn:
    Description: ARN of the Role created for Ping Function
    Value: !GetAtt PingFunctionRole.Arn
  PingFunctionArn:
    Description: ARN of the Ping Function
    Value: !GetAtt PingFunction.Arn
  PingEventBusArn:
    Description: ARN of the Ping Event Bus
    Value: !GetAtt Ping.Arn
    # Export:
    #   Name: PingEventBusArn