version: "3"

volumes:
  node_modules:

services:
  thunder-console:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/src
      - node_modules:/src/node_modules
    environment:
      - NODE_ENV=development