# syntax = docker/dockerfile:1

ARG NODE_VERSION=24

FROM node:${NODE_VERSION}-alpine as base

# Add repos 
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories && \
    echo "http://dl-cdn.alpinelinux.org/alpine/edge/community/" >> /etc/apk/repositories && \
    apk update

# Install deps
RUN apk add --no-cache \
    bash \
    curl \
    git \
    zip \
    python3 \
    ca-certificates 

ENV NODE_ENV=development
ENV SHELL=/bin/bash

# Install Bun
RUN curl -fsSL https://bun.sh/install | bash
ENV PATH="/root/.bun/bin:${PATH}"

# Clear cache
RUN rm -rf /var/cache/apk/*

WORKDIR /src

CMD ["bash", "-c"]

# Build
FROM base AS build

COPY package.json ./
RUN bun install

# Run
FROM base

COPY --from=build /src/node_modules /src/node_modules

CMD [ "bun", "run", "dev" ]