# syntax = docker/dockerfile:1

ARG NODE_VERSION=24

FROM node:${NODE_VERSION}-alpine as base

ENV NODE_ENV=development

WORKDIR /src

# Build
FROM base as build

COPY --link package.json ./
RUN npm install

# Run
FROM base

COPY --from=build /src/node_modules /src/node_modules

CMD [ "npm", "run", "dev" ]