name: Release to Production

on:
  workflow_dispatch:
    inputs:
      workspace:
        description: 'Workspace to deploy'
        required: true
        type: choice
        options:
          - all
          - console
          - services-all
          - services-provider
          - services-ping
          - services-runner
          - supabase-all
          - supabase-notification
          - supabase-github
          - supabase-polar

concurrency:
  group: production-deploy-${{ github.ref }}
  cancel-in-progress: false

env:
  AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}

jobs:
  deploy-console:
    name: Deploy Console to Production
    runs-on: ubuntu-latest
    if: contains('all,console', github.event.inputs.workspace)
    environment:
      name: production
      url: 'https://console.thunder.so'
    env:
      # aws
      NODE_ENV: production
      SITE_URL: ${{ secrets.SITE_URL }}
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # supabase
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      # services
      PROVIDER_STACK: ${{ secrets.PROVIDER_STACK }}
      RUNNER_REGION: ${{ secrets.RUNNER_REGION }}
      RUNNER_ASSUME_ROLE_ARN: ${{ secrets.RUNNER_ASSUME_ROLE_ARN }}
      RUNNER_SERVICE: ${{ secrets.RUNNER_SERVICE }}
      # github
      GH_APP: ${{ secrets.GH_APP }}
      GH_APP_ID: ${{ secrets.GH_APP_ID }}
      GH_PRIVATE_KEY: ${{ secrets.GH_PRIVATE_KEY }}
      GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }}
      GH_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
      # polar
      POLAR_SERVER: ${{ secrets.POLAR_SERVER }}
      POLAR_ACCESS_TOKEN: ${{ secrets.POLAR_ACCESS_TOKEN }}
      POLAR_CHECKOUT_SUCCESS_URL: ${{ secrets.POLAR_CHECKOUT_SUCCESS_URL }}      
      # posthog
      POSTHOG_HOST: ${{ secrets.POSTHOG_HOST }}
      POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: cd apps/console && bun install --linker=isolated

      - name: Build console
        run: cd apps/console && bun run build

      - name: Deploy to AWS
        run: cd apps/console && npx cdk deploy --app "npx tsx stack/production.ts" --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

  deploy-services-all:
    name: Deploy All Services to Production
    runs-on: ubuntu-latest
    if: github.event.inputs.workspace == 'services-all' || github.event.inputs.workspace == 'all'
    environment:
      name: production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.RUNNER_REGION }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: cd services && bun install --linker=isolated

      - name: Deploy all services to production
        run: cd services && bun run cdk deploy --app "npx tsx bin/ping.ts && npx tsx bin/provider.ts && npx tsx bin/runner.ts" --context environment=production

  deploy-services-provider:
    name: Deploy Provider Service to Production
    runs-on: ubuntu-latest
    if: github.event.inputs.workspace == 'services-provider'
    environment:
      name: production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: cd services && bun install --linker=isolated

      - name: Deploy provider service to production
        run: cd services && bun run cdk deploy --app "npx tsx bin/provider.ts" --context environment=production

  deploy-services-runner:
    name: Deploy Runner Service to Production
    runs-on: ubuntu-latest
    if: github.event.inputs.workspace == 'services-runner'
    environment:
      name: production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: cd services && bun install --linker=isolated

      - name: Deploy runner service to production
        run: cd services && bun run cdk deploy --app "npx tsx bin/runner.ts" --context environment=production

  deploy-services-ping:
    name: Deploy Ping Service to Production
    runs-on: ubuntu-latest
    if: github.event.inputs.workspace == 'services-ping'
    environment:
      name: production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: cd services && bun install --linker=isolated

      - name: Deploy ping service to production
        run: cd services && bun run cdk deploy --app "npx tsx bin/ping.ts" --context environment=production

  deploy-supabase-all:
    name: Deploy All Supabase Functions to Production
    runs-on: ubuntu-latest
    if: github.event.inputs.workspace == 'supabase-all' || github.event.inputs.workspace == 'all'
    environment:
      name: production
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      GH_WEBHOOK_SECRET: ${{ secrets.GH_WEBHOOK_SECRET }}
    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Install Deno
        run: curl -fsSL https://deno.land/install.sh | sh -s v2.2.15

      - name: Install notification-webhook dependencies
        run: |
          export PATH="$HOME/.deno/bin:$PATH"
          source $HOME/.bash_profile 
          cd supabase/functions/notification-webhook && deno install

      - name: Deploy all supabase functions to production
        run: |
          cd supabase
          supabase functions deploy notification-webhook --no-verify-jwt --project-ref $SUPABASE_PROJECT_ID
          supabase functions deploy github-webhook --no-verify-jwt --project-ref $SUPABASE_PROJECT_ID
          supabase functions deploy polar-webhook --no-verify-jwt --project-ref $SUPABASE_PROJECT_ID

  deploy-supabase-notification:
    name: Deploy notification-webhook to Production
    runs-on: ubuntu-latest
    if: github.event.inputs.workspace == 'supabase-notification'
    environment:
      name: production
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Install Deno
        run: curl -fsSL https://deno.land/install.sh | sh -s v2.2.15

      - name: Install notification-webhook dependencies
        run: |
          export PATH="$HOME/.deno/bin:$PATH"
          source $HOME/.bash_profile 
          cd supabase/functions/notification-webhook && deno install

      - name: Deploy notification-webhook to production
        run: |
          cd supabase
          supabase functions deploy notification-webhook --no-verify-jwt --project-ref $SUPABASE_PROJECT_ID

  deploy-supabase-github:
    name: Deploy github-webhook to Production
    runs-on: ubuntu-latest
    if: github.event.inputs.workspace == 'supabase-github'
    environment:
      name: production
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      GH_WEBHOOK_SECRET: ${{ secrets.GH_WEBHOOK_SECRET }}
    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy github-webhook to production
        run: supabase functions deploy github-webhook --no-verify-jwt --project-ref $SUPABASE_PROJECT_ID

  deploy-supabase-polar:
    name: Deploy polar-webhook to Production
    runs-on: ubuntu-latest
    if: github.event.inputs.workspace == 'supabase-polar'
    environment:
      name: production
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Deploy polar-webhook to production
        run: supabase functions deploy polar-webhook --no-verify-jwt --project-ref $SUPABASE_PROJECT_ID
